### ISSUE TITLE
Issues with the .exe file

### ISSUE THREAD

**Issue by ankushgoel27** [rasta-mouse/CookieMonster#1]
Hi,

Is the .exe file created not standalone? When i run the file in the release folder, it works fine but when i copy the CookieMonster.exe file out of that folder and place it anywhere else, it gives an error. 

"Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CommandLine, Version=2.3.0.0, Culture=neutral, PublicKeyToken=de6f01bd326f8c32' or one of its dependencies. The system cannot find the file specified.
   at CookieMonster.Program.Main(String[] args)"

I think its dependent on other DLL files.

Please help.

**Comment by rasta-mouse** [comment]
Yeah, at the moment it needs those DLLs.  A quick workaround would be to use ILMerge or Costura.Fody.
